spring.application.name=authify
#
## Local default uses your NEW Public Proxy
#spring.datasource.url=${DB_URL:jdbc:mysql://interchange.proxy.rlwy.net:20316/railway}
#spring.datasource.username=${DB_USER:root}
#spring.datasource.password=${DB_PASSWORD:VnPfDrQUPLyjjmziORuvuMXnwLqbGgPp}
#
## Explicitly set the dialect to prevent startup crashes
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#
#server.port=${PORT:8081}
#server.servlet.context-path=/api
#
## Security & Mail
#jwt.secret.key=${JWT_SECRET:yourverylongandsecurerandomsecretkeyhereatleast32chars}
#spring.mail.host=smtp-relay.brevo.com
#spring.mail.port=587
#spring.mail.username=9f1a11001@smtp-brevo.com
#spring.mail.password=bsk1jG2yoftK3Od
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.protocol=smtp
#spring.mail.properties.mail.smtp.from=kedargajmal8@gmail.com





spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8081}
server.servlet.context-path=/api

jwt.secret.key=${JWT_SECRET:yourverylongandsecurerandomsecretkeyhereatleast32chars}

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=9f1a11001@smtp-brevo.com
spring.mail.password=bsk1jG2yoftK3Od
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=kedargajmal8@gmail.com